### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:10001

### ISSUE THREAD

**Issue by robbiew** [dinchak/doornode#1]
I'm attempting to setup Doornode and I've installed/configured both BRE and TW2002... But when I connect via the debug server (port 1234) and attempt to launch each door, I receive this console error:

```
New connection from ::ffff:192.168.1.187, 1 active connections
Error: connect ECONNREFUSED 127.0.0.1:10001
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1104:14)
Failed to connect to port 10001 after 20 tries, giving up
Connection from ::ffff:192.168.1.187 closed, 0 active connections
```

The error repeats many times and then the connection is dropped.

EDIT: Dosbox paths are correct (I've tried on Ubuntu 18.04 and Raspian/RPI4).

Any idea what I may be wrong?

Great app!

**Comment by robbiew** [comment]
SOLVED. Needed to run w/ sudo :)

`sudo node ./app.js`

**Comment by dinchak** [comment]
Happy to hear you figured it out! There is also a method of elevating permissions to open privileged ports without granting full root access to the process documented on the project README.  Best of luck :)

**Comment by robbiew** [comment]
Hey there, looks like it wasn't an elevated port issue after all. I'm still having the issue with brand-new install I've tried on Rpi4, Ubuntu VM and Windows. I've configured quite a few games (BRE, SRE, Exitilus, Lord, Lord2, TW2002), and still get this console error when I try and launch a game:

`Error: connect ECONNREFUSED 127.0.0.1:10001`

Also, I don't see the Dosbox console opening when I launch a game (even with headless=false), and config path to dosbox executable is correct...

Any ideas? Thanks!

**Comment by dinchak** [comment]
Hey Robbie! Sorry to hear you're having trouble!

I believe the port 10001 connection refused error is because dosbox is failing to start the door and is exiting out before it really opens up the nullmodem server.  Unfortunately it could be a number of reasons why it isn't working.

There should be a `dosbox1.conf` file in the `doornode/dosbox` directory.  Try running dosbox manually using that config file from inside the `doornode/dosbox` directory:

`dosbox -conf dosbox1.conf`

It should drop you at a C:\> prompt.  From here you can run the batch files manually and try to see what might be going wrong.  If everything seems right, you can add the additional arguments that doornode uses to launch the doors (and make sure they exit cleanly).  Here is an example of the full command line doornode uses when executing:

(CWD is the `/Users/tom/src/doornode/dosbox` directory)

`/usr/local/bin/dosbox /Users/tom/src/doornode/dosbox/drive/bin/exit.bat -c C:\\doors\\bin\\bre.bat -conf dosbox1.conf -exit`

Hopefully through experimenting with the command line options you can track down what's causing it.  Let me know how it goes!

**Comment by robbiew** [comment]
Thank you, it's [solved] -- for real this time :)

FYI - your snippet allowed me track down my error (I edited first part to point to dosbox executable, i think that was a typo?):

e.g., for me:

`/usr/bin/dosbox /doornode/dosbox/drive/bin/exit.bat -c C:\\doors\\bin\\bre.bat -conf dosbox1.conf -exit`

Thanks again for creating this!
